name: eliud_pkg_chat
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^1.0.0

  eliud_core:
    path: ../eliud_core

  eliud_pkg_follow:
    path: ../eliud_pkg_follow

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
