---
name: eliud_pkg_chat
description: eliud_pkg_chat is a package to provide chat functionality to an app.
  More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_chat
version: 1.1.7
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core: ^1.1.6
  eliud_core_main: ^1.0.2
  eliud_core_helpers: ^1.0.0
  eliud_pkg_chat_model: ^1.0.0
  eliud_pkg_follow: ^1.1.7
  eliud_pkg_follow_model: ^1.0.0
  eliud_pkg_medium: ^1.1.6
  eliud_core_model: ^1.0.0
  bloc: ^8.1.2
  cloud_firestore: ^4.13.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  transparent_image: ^2.0.1
  tuple: ^2.0.2
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: ^1.1.7
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
platforms:
  android: null
  ios: null
  web: null
