---
name: eliud_pkg_chat
description: eliud_pkg_chat is a package to provide chat functionality to an app.
  More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_chat
version: 1.1.5+5
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core:                                                                                        # ANDROID IOS             WEB
    path: ../eliud_core
  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main
  eliud_core_helpers:                                                                                # ANDROID IOS             WEB
    path: ../eliud_core_helpers
  eliud_pkg_chat_model:                                                                              # ANDROID IOS             WEB
    path: ../eliud_pkg_chat_model
  eliud_pkg_follow:                                                                                  # ANDROID IOS             WEB
    path: ../eliud_pkg_follow
  eliud_pkg_follow_model:                                                                            # ANDROID IOS             WEB
    path: ../eliud_pkg_follow_model
  eliud_pkg_medium:                                                                                  # ANDROID IOS             WEB
    path: ../eliud_pkg_medium

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
platforms:
  android: null
  ios: null
  web: null
