name: eliud_pkg_chat
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^2.0.1

  chat_bubbles:
    path: ../../chat_bubbles

  eliud_core:
    path: ../eliud_core

  eliud_pkg_follow:
    path: ../eliud_pkg_follow

#  eliud_pkg_create:
#    path: ../eliud_pkg_create

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - assets/images/
